language: python

python:
  - 3.3

install:
  - conda update conda --yes
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION matplotlib pandas pip six nose openpyxl
  - conda update conda --yes
  - source activate testenv
  - pip install .
  - cp test/matplotlibrc .

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH

script: nosetests --verbose --with-id
