language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  # Default values for common packages, override as needed
  global:
    - COVERAGE=false

matrix:
  fast_finish: true
  include:
  - python: 3.4
    env:
    - COVERAGE=true

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

install:
  - conda update conda --yes
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION matplotlib pandas pip six nose openpyxl
  - source activate testenv
  - pip install coveralls
  - pip install .
  - cp test/matplotlibrc ~/matplotlibrc

script:
  - cd ~
  - source activate testenv
  - python -c "import metar; metar.test()"

after_success:
  - if [ ${COVERAGE} = true ]; then coveralls fi
