language: python

matrix:
  fast_finish: true
  include:

    - python: 2.7
      env:
        - COVERAGE=true
    - python: 3.3
      env:
        - COVERAGE=false
    - python: 3.4
      env:
        - COVERAGE=false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

install:
  - conda update conda --yes
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION seaborn pandas pip six nose openpyxl
  - source activate testenv
  - pip install coveralls
  - pip install .
  - cp test/matplotlibrc .

script:
  - nosetests --with-coverage --cover-package=metar --verbose

after_success:
  - if [ ${COVERAGE} = true ]; then coveralls; fi
